name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version-file: '.python-version'
        
    - name: Install uv
      uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3
      with:
        version: "latest"
        enable-cache: true
      
    - name: Install dependencies
      run: uv sync --dev
        
    - name: Type check with MyPy
      run: uv run mypy docker_compose_mcp/

  build:
    name: Build package
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version-file: '.python-version'
        
    - name: Install uv
      uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3
      with:
        version: "latest"
        enable-cache: true
      
    - name: Install dependencies
      run: uv sync --dev
      
    - name: Build package
      run: uv build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: dist
        path: dist/

  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    environment: test
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
    
    services:
      docker:
        image: docker:dind
        options: --privileged
    
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install uv
      uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3
      with:
        version: "latest"
        enable-cache: true
      
    - name: Install dependencies
      run: uv sync --dev
        
    - name: Run unit tests
      run: uv run pytest tests/test_docker_compose_manager.py -v
        
    - name: Run MCP integration tests (without Docker)
      run: uv run pytest tests/test_mcp_integration.py -v -k "not integration"
        
    - name: Run Docker integration tests
      run: uv run pytest tests/test_mcp_integration.py::TestRealDockerIntegration -v -m integration
        
    - name: Generate coverage report
      run: uv run pytest --cov=docker_compose_mcp --cov-report=xml --cov-report=term-missing
      if: matrix.python-version == '3.13'
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
      if: matrix.python-version == '3.13'
      with:
        fail_ci_if_error: true
        use_oidc: true
