name: Code Review with ReviewDog

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  vorpal:
    name: Vorpal Security Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Vorpal Security Code Review
      uses: checkmarx/vorpal-reviewdog-github-action@v1.0.0
      with:
        level: warning
        reporter: github-pr-review
        filter_mode: diff_context
        fail_on_error: true