name: Code Review with ReviewDog

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  vorpal:
    name: Vorpal Security Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Vorpal Security Code Review
      uses: checkmarx/vorpal-reviewdog-github-action@8cc292ff48b7b0c94de87be0cbd5a5b50c5bbf8c # v1.2.0
      with:
        level: warning
        reporter: github-pr-review
        filter_mode: diff_context
        fail_on_error: true
