name: ReviewDog

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  bandit:
    name: Bandit Security Analysis
    runs-on: ubuntu-latest
    environment: analysis
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Run Bandit Security Analysis
      uses: brunohaf/action-bandit@52689a12ef6e1a03cfc46991158742ad271bc84e # v1.2.1
      with:
        bandit_config: pyproject.toml
        reporter: github-pr-review
        level: warning
        fail_on_error: true
        filter_mode: diff_context

  pyright:
    name: Pyright Type Checking
    runs-on: ubuntu-latest
    environment: analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: jordemort/action-pyright@v1
        with:
          reporter: github-pr-review
          level: warning
          fail_on_error: true
          filter_mode: diff_context
          lib: true

  ruff:
    name: Ruff Code Analysis
    runs-on: ubuntu-latest
    environment: analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: benny123tw/action-ruff@226d241bdf7205e6e048f1407d21bd69a64b7298 # v1.1.0
        with:
          reporter: github-pr-review
          level: warning
          fail_level: warning
          filter_mode: diff_context
