name: Security Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  pull-requests: write
  checks: write

jobs:
  bandit:
    name: Bandit Security Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Run Bandit Security Analysis
      uses: brunohaf/action-bandit@a7ca89e99fa9ff26ce8b0b8fcead6b9d3e84ca36 # v1.2.1
      with:
        bandit_config: pyproject.toml
        reporter: github-pr-review
        level: warning
        fail_on_error: false
        tool_name: bandit-security
        filter_mode: added