name: Code Style Check

on:
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    name: Ruff Linting and Formatting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Install Ruff
      uses: astral-sh/ruff-action@0c50076f12c38c3d0115b7b519b54a91cb9cf0ad # v3.5.0

    - name: Run Ruff Check
      run: ruff check

    - name: Run Ruff Format Check
      run: ruff format --check